### PR TITLE
Adds a new table format output

### PR DESCRIPTION
**Pull request by 0x346e3730**
This PR adds a new output format : a table.

Here is how it looks like :
image

Feedbacks more than welcome

### CODE REVIEW

**Comment by nunomaduro** [comment]
Really appreciate that you toke the time to make this proposal. However, not having a table is an intentional decision on this project.

**Comment by nunomaduro** [comment]
@0x346e3730 Let me know if you would like to be added as maintainer of this project, so you can help review pull request, discuss the future of it, etc.

**Comment by 0x346e3730** [comment]
Sure, why not. I don't understand why you didn't wanted a table output though ?

**Comment by nunomaduro** [comment]
It's not prettier.

**Pull request closed without merging**
